name: dry

on:
  push:
    tags:
      - "^v\d+\.\d+(\.\d+)?(-\S*)?$"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set tag env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registry.sev-2.com/demo/dry:${{ env.RELEASE_VERSION }}
  deploy:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
    - name: Set tag env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Deploy
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: set image deployment/dry dry=registry.sev-2.com/demo/dry:${{ env.RELEASE_VERSION }} -n demo
